### ISSUE TITLE
Support pnpm

### ISSUE THREAD

**Issue by jayvdb** [simonkberg/nyr#23]
It would be great if this also supported [pnpm](https://pnpm.js.org).

Not sure if [ied](https://www.npmjs.com/package/ied) is also worth supporting, as it doesnt appear to be under active maintenance.

Other pms listed at https://htr3n.github.io/2018/04/node.js-package-managers-npm-and-yarn/ might also be possible.

**Comment by simonkberg** [comment]
Thanks for opening the issue. I have decided to deprecate this package.

I don't recommend this package and consider its usage a bad practice. Collaborators to your project should all use the same package manager to guarantee reproducible builds. Instead of supporting ambiguous usage of different package manager for collaboration on your project, you should enforce the usage of just one.

Released versions will continue to work but are unsupported and contain dependencies with known security vulnerabilities. Use at your own risk.
